# Generated by Django 5.2.1 on 2025-06-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('entrenador', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='equipos/fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('numero_camiseta', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/fotos/')),
                ('ficha_pdf', models.FileField(blank=True, null=True, upload_to='jugadores/pdfs/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.equipo')),
            ],
        ),
    ]
